import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import addToCart from "../../Assets/Projects/addtocart-removebg-preview.png";
import weather from "../../Assets/Projects/weather-removebg-preview.png";
import youtube from "../../Assets/Projects/youtube-removebg-preview.png";
import random from "../../Assets/Projects/random-removebg-preview.png";
import netflix from "../../Assets/Projects/netflix-removebg-preview.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={youtube}
              isBlog={false}
              title="Youtube"
              description="2023 YouTube clone || This project is a front-end clone of the popular video-sharing platform, YouTube. It aims to recreate the familiar and user-friendly interface of YouTube, allowing users to browse, search, and watch videos seamlessly."
              ghLink="https://github.com/Ankit91153/youTube-Lite"
              demoLink="https://you-tube-lite.netlify.app"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={netflix}
              isBlog={false}
              title="Netflix"
              description="A Netflix clone project is a web application or mobile app that replicates the functionality and features of the original Netflix platform. The project involves creating a user-friendly interface ."
              ghLink="https://github.com/Ankit91153/netflixClone"
              demoLink="https://ankit91153.github.io/netflixClone/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={weather}
              isBlog={false}
              title="Weather Website"
              description="I was tired of going out and seeing what the weather was like outside. Tired of using the google weather application. This simple weather application will only display the current weather for a given area."
              ghLink="https://github.com/Ankit91153/weatherApp"
              demoLink="https://weather-app-by-ankit.onrender.com/"              
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={addToCart}
              isBlog={false}
              title="Add-To-Cart"
              description="Shopping cart app built with React and React-Toolkit. This app is a clone of react javascript ecommerce  shopping-cart ...."
              ghLink="https://github.com/Ankit91153/e-commerce-website"
              demoLink="https://e-commerce-website-react-nine.vercel.app/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={random}
              isBlog={false}
              title="Guess Number"
              description="The game is to guess a random number generated by a computer in the range 1 – 100 in a minimum number of Guesses."
              ghLink="https://github.com/Ankit91153/Number-Guesses-Game"
              demoLink="https://ankit91153.github.io/Number-Guesses-Game/" 
            />
          </Col>

          
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
